import Link from "next/link";

export default function TermsPage() {
    return (
        <main className="min-h-screen bg-[var(--bg-base)] px-4 py-16">
            <div className="max-w-2xl mx-auto flex flex-col gap-8">
                <div className="flex flex-col gap-2">
                    <Link href="/" className="text-sm text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-colors">
                        ← Back to InlineExplainer
                    </Link>
                    <h1 className="text-3xl font-bold text-[var(--text-primary)] mt-2">Terms of Service</h1>
                    <p className="text-sm text-[var(--text-muted)]">Last updated: June 2026</p>
                </div>

                <div className="flex flex-col gap-6 text-[var(--text-secondary)] text-sm leading-relaxed">
                    <p>
                        InlineExplainer is a free, non-commercial student portfolio project built to demonstrate
                        software engineering skills. By using it, you agree to the terms below.
                    </p>

                    <section className="flex flex-col gap-2">
                        <h2 className="text-lg font-semibold text-[var(--text-primary)]">1. What this app is</h2>
                        <p>
                            InlineExplainer lets you paste a public GitHub, GitLab, or Bitbucket repository URL and explore
                            its code through AI-generated explanations and a conversational assistant. It is provided
                            as-is, free of charge, with no guarantee of uptime, accuracy, or availability. It runs entirely
                            on free-tier infrastructure and may be slow, unavailable, or discontinued at any time without notice.
                        </p>
                    </section>

                    <section className="flex flex-col gap-2">
                        <h2 className="text-lg font-semibold text-[var(--text-primary)]">2. Acceptable use</h2>
                        <p>You agree to use InlineExplainer only to:</p>
                        <ul className="list-disc pl-5 flex flex-col gap-1">
                            <li>Analyze <strong>public</strong> repositories that you have the right to view and process.</li>
                            <li>Use the AI explanation and chat features for legitimate learning, review, or exploration purposes.</li>
                        </ul>
                        <p>You agree not to:</p>
                        <ul className="list-disc pl-5 flex flex-col gap-1">
                            <li>Attempt to overload, abuse, or circumvent the app's rate limits or infrastructure.</li>
                            <li>Use the app to process repositories containing malware, illegal content, or content you don't have the right to access.</li>
                            <li>Attempt to extract, scrape, or resell the app's AI-generated output at scale.</li>
                        </ul>
                    </section>

                    <section className="flex flex-col gap-2">
                        <h2 className="text-lg font-semibold text-[var(--text-primary)]">3. AI-generated content</h2>
                        <p>
                            Explanations and chat responses are generated by third-party large language models (NVIDIA NIM
                            and Google Gemini) and may be incomplete, outdated, or incorrect. InlineExplainer does not
                            guarantee the accuracy of any AI-generated explanation. Always verify important conclusions
                            against the actual source code.
                        </p>
                    </section>

                    <section className="flex flex-col gap-2">
                        <h2 className="text-lg font-semibold text-[var(--text-primary)]">4. No warranty, no liability</h2>
                        <p>
                            This is a student project, not a commercial product. It is provided without any warranty of
                            any kind, express or implied. The developer is not liable for any loss, damage, or issue arising
                            from your use of the app, including but not limited to data loss, service interruption, or
                            reliance on AI-generated content.
                        </p>
                    </section>

                    <section className="flex flex-col gap-2">
                        <h2 className="text-lg font-semibold text-[var(--text-primary)]">5. Changes to these terms</h2>
                        <p>
                            These terms may be updated as the project evolves — for example, when an account-deletion
                            feature or other functionality changes how the app handles your data. Continued use of the app
                            after changes are posted constitutes acceptance of the revised terms.
                        </p>
                    </section>

                    <section className="flex flex-col gap-2">
                        <h2 className="text-lg font-semibold text-[var(--text-primary)]">6. Contact</h2>
                        <p>
                            Questions about these terms can be sent to{" "}
                            <a href="mailto:ameyasingh619@gmail.com" className="text-[var(--text-primary)] underline hover:no-underline">ameyasingh619@gmail.com</a>.
                        </p>
                    </section>
                </div>
            </div>
        </main>
    );
}